
/** 
 * Incomplete list of file formats used in IA Items 
 */
export const IA_FILE_FORMATS = [
    "Unknown",
    "3GP Audio",
    "7z",
    "24bit Flac",
    "56Kb QuickTime",
    "64Kb MPEG4",
    "64kbps M3U",
    "64Kbps MP3",
    "64Kb QuickTime",
    "96Kbps MP3",
    "128kbps M3U",
    "128Kbps MP3",
    "160Kbps MP3",
    "192Kbps MP3",
    "256Kb MPEG4",
    "256Kbps MP3",
    "256Kb QuickTime",
    "320Kbps MP3",
    "512Kb MPEG4",
    "Abbyy GZ",
    "Abbyy HTML",
    "ABBYY XML",
    "Abbyy ZIP",
    "ACS Encrypted EPUB",
    "ACS Encrypted PDF",
    "Additional Text PDF",
    "Adobe Illustrator",
    "Advanced Audio Coding",
    "AIFF",
    "Amiga Disk File",
    "Android Package Archive",
    "Animated GIF",
    "Apple Audiobook",
    "ARC CDX Index",
    "Archive BitTorrent",
    "ARC Named Entities GZ",
    "ARC Transformation GZ",
    "ASR",
    "Audacity Project",
    "Audio Transclusion Contents",
    "AVIF Thumbnails ZIP",
    "Backup",
    "BDRC Outline",
    "Berkeley DB Java Edition",
    "Biodiversity Heritage Library METS",
    "Bitmap Image",
    "BitTorrent",
    "BitTorrentContents",
    "Book Cover",
    "Book Cover Image",
    "Braille Ready Format",
    "BZIP2",
    "Cascading Style Sheet",
    "Catalog History CSV",
    "CD Audio Track Shortcut",
    "CD Datafiles Zip",
    "Censor as Music JSON",
    "Checksums",
    "chOCR",
    "Cinepack",
    "Closed Caption Text",
    "Closed Caption Text Disc",
    "Closed Caption Text OCR",
    "Cloth Cover Detection Log",
    "Columbia Fingerprint",
    "Columbia Fingerprint TV",
    "Columbia Peaks",
    "Columbia Sparse Fingerprint TV",
    "Comic Book RAR",
    "Comic Book TAR",
    "Comic Book ZIP",
    "Comma-Separated Values",
    "Comma-Separated Values GZ",
    "Compiled HTML",
    "Content Addressable aRchive",
    "Content Addressable aRchive Log",
    "Content Addressable aRchive Trigger",
    "Contents",
    "Corrected Abbyy HTML",
    "Crowley IDF",
    "Crowley QPF",
    "Cue Sheet",
    "CUIL",
    "DAT",
    "Democracy Now Text",
    "Derivation Rules",
    "Development Scandata",
    "Digital Asset Exchange",
    "Digital Theater Systems Audio",
    "DivX",
    "DjVu",
    "DjVuTXT",
    "Djvu XML",
    "Dublin Core",
    "DVD Info",
    "DVD Info Backup",
    "DV Video",
    "Emulator Screenshot",
    "Encrypted DAT",
    "Encrypted Internet Archive ARC GZ",
    "Encrypted Web ARChive GZ",
    "EPUB",
    "Essentia High GZ",
    "Essentia Low GZ",
    "Excel",
    "Extended Data Services",
    "Extra Metadata JSON",
    "FictionBook 2.0",
    "Flac",
    "Flac FingerPrint",
    "Flash Authoring",
    "Flash Video",
    "Flippy ZIP",
    "Frictionless Data Package Descriptor JSON",
    "Generic Raw Book Tar",
    "Generic Raw Book Zip",
    "GL Transmission Format",
    "Grayscale PDF",
    "GZIP",
    "GZipped TAR",
    "h.264",
    "h.264 720P",
    "h.264 HD",
    "h.264 IA",
    "h.264 MPEG4",
    "h.264 popcorn",
    "h.264/MPEG2-TS",
    "HEIF",
    "HeritrixCrawlLog",
    "HeritrixJob",
    "HEVC",
    "HiRes MPEG4",
    "hOCR",
    "HTML",
    "Image-Only PDF Metadata JSON",
    "Image Container PDF",
    "Information",
    "Intermediate ASR JSON",
    "Internet Archive ARC",
    "Internet Archive ARC GZ",
    "iOS App Store Package",
    "ISO Image",
    "Item CDX Index",
    "Item CDX Meta-Index",
    "Item CDX Summary",
    "Item Image",
    "Item Tile",
    "IV50",
    "JPEG",
    "JPEG-Compressed PDF",
    "JPEG 250px Thumb",
    "JPEG 500px Thumb",
    "JPEG 1200px Thumb",
    "JPEG 2000",
    "JPEG from Video",
    "JPEG Thumb",
    "JPEG Thumb Large",
    "JSON",
    "JSON GZ",
    "JSON SRT",
    "LCP Encrypted Audiobook",
    "LCP Encrypted EPUB",
    "LCP Encrypted PDF",
    "LibriVox Apple Audiobook",
    "List Inversion Log",
    "Log",
    "Longitudinal Graph Analysis TGZ",
    "M3U",
    "Mac OS X Disk Image",
    "Magnet URI",
    "MARC",
    "MARC Binary",
    "MARC Source",
    "Matroska",
    "MBOX GZ",
    "Metadata",
    "Metadata Log",
    "METS",
    "Micro Cards Data JSON",
    "Micro Cards JP2 ZIP",
    "Microfiche Partition JSON",
    "Microfiche Partition Log",
    "Microfilm Issues JSON",
    "Microfilm Issues Log",
    "Microsoft Reader",
    "MIDI",
    "MOBI",
    "Motion JPEG",
    "Movie Frames",
    "Movies Transclusion Contents",
    "MP3",
    "MP3 Sample",
    "MPEG-4 Audio",
    "MPEG1",
    "MPEG2",
    "MPEG2-TS",
    "MPEG4",
    "MPEGTS/Thumbnail",
    "MPEGTS Demux",
    "MusicBrainz Metadata",
    "MusicXML",
    "Name Metadata",
    "NRT",
    "NRT Processed",
    "OCLC xISBN JSON",
    "OCLC xISBN ZIP",
    "OCR Page Index",
    "OCR Search Text",
    "Ogg Theora",
    "Ogg Video",
    "Ogg Vorbis",
    "OpenDocument Presentation",
    "OpenDocument Spreadsheet",
    "OpenDocument Text Document",
    "OpenType Font",
    "Original DjVu",
    "Page Numbers JSON",
    "PalmOS Database",
    "PalmOS Plucker",
    "Parsed GZ",
    "PersonalArchive",
    "PersonalArchiveLog",
    "PNG",
    "Powerpoint",
    "Preliminary Scandata",
    "QuickTime",
    "RAR",
    "Raw BDRC Book Zip",
    "Raw China Books RAR Tar",
    "Raw China Books RAR Zip",
    "Raw China Book Zip",
    "Raw Cornell Book Zip",
    "Raw Mekel Tar",
    "Raw Michigan Book Zip",
    "Raw NIH Book Zip",
    "Raw Yale Book Zip",
    "Raw Yale Medical Book Zip",
    "Real Audio",
    "Real Media",
    "Recoded Text PDF",
    "Remediated EPUB",
    "RePublisher Corrections Processing Log",
    "RePublisher Final Processing Log",
    "RePublisher Foldouts Processing Log",
    "RePublisher Full Tar",
    "RePublisher Initial Processing Log",
    "RePublisher Proxy Tar",
    "RePublisher Trigger Text",
    "Resume TAR GZ",
    "Rich Text Format",
    "Scandata",
    "Scan Factors",
    "Scribe Scandata ZIP",
    "Segment Data",
    "Segments",
    "SHNtool MD5 Checksums",
    "Shockwave Flash",
    "Shorten",
    "Sibelius",
    "Simple File Verification",
    "Simple List JSONL",
    "SimpleLists Archival Backup",
    "Single Book Page Text",
    "Single Page B/W JPG ZIP",
    "Single Page FIXME JPEG Tar",
    "Single Page FIXME JPEG ZIP",
    "Single Page Library JP2 Tar",
    "Single Page Library JP2 ZIP",
    "Single Page Library TIFF ZIP",
    "Single Page Original CR2 Tar",
    "Single Page Original JP2 Tar",
    "Single Page Original JP2 ZIP",
    "Single Page Original JPEG Tar",
    "Single Page Original JPEG ZIP",
    "Single Page Original TIFF ZIP",
    "Single Page Processed JP2 Tar",
    "Single Page Processed JP2 ZIP",
    "Single Page Processed JPEG Tar",
    "Single Page Processed JPEG ZIP",
    "Single Page Processed TIFF ZIP",
    "Single Page Pure JP2 Tar",
    "Single Page Pure JP2 ZIP",
    "Single Page Raw JP2 Tar",
    "Single Page Raw JP2 ZIP",
    "Single Page Raw JPEG Tar",
    "Single Page Raw JPEG ZIP",
    "Single Page Watermark JP2 ZIP",
    "Single Page Zipped PDF",
    "Sony Reader Format",
    "Spectrogram",
    "Speech Confidence JSON",
    "Speech VS Music JSON",
    "Storage Media Image",
    "Storj Upload Log",
    "Storj Upload Trigger",
    "Structural Metadata",
    "SubRip",
    "Symlink Instructions",
    "Tab-Separated Values",
    "TAR",
    "Text",
    "Text PDF",
    "Text PDF Metadata JSON",
    "Texts Transclusion Contents",
    "TGZiped Text Files",
    "Thumbnail",
    "TIFF",
    "Title Page Detection Log",
    "Torrent Info DAT",
    "TrueType Font",
    "TTScribe Preimage ZIP",
    "TTScribe RAW Preimage ZIP",
    "TV Align SubRip",
    "TV Electronic Program Guide",
    "TV Text Stream",
    "Uncompressed Image-Only PDF",
    "VBR M3U",
    "VBR MP3",
    "Video Index",
    "VOB",
    "WARC CDX Index",
    "WARC HostLinks GZ",
    "WARC Named Entities GZ",
    "WARC Transformation GZ",
    "WARC UrlLinks Log",
    "WAVE",
    "WebA",
    "Web ARChive",
    "Web Archive Collection Zipped",
    "Web ARChive GZ",
    "Web ARChive ZST",
    "Webex Advanced Recording File",
    "WebM",
    "Web Open Font Format",
    "Web Open Font Format 2.0",
    "Web Video Text Tracks",
    "Whisper ASR JSON",
    "Windows Executable",
    "Windows Media",
    "Windows Media Audio",
    "Windows Screensaver",
    "Word Document",
    "ZIP",
    "Zotero RDF"
] as const;


/**
 * Type containing common IA file formats.
 */
export type IaFileFormat = typeof IA_FILE_FORMATS[number] | (string & {});