import { IaBaseMetadataType, IaFileFormat, IaFileRotation, IaFileSource, IaRawMetadata, Optional, Prettify, IA_FILE_FORMATS } from ".";


export type IaFileMetadataRaw<T extends IaFileBaseMetadata = IaFileBaseMetadata> = IaRawMetadata<T>;

export type IaFilesXmlMetadata = Omit<Optional<IaFileExtendedMetadata, 'mtime' | 'size'>, 'name'> & { name: `${string}_files.xml`; };


export type IaFileBasicMetadata<NameType extends string = string> = {
    /** Path to file name */
    readonly name: NameType;
    /** 
     * Indicates the type (format) of file. See tab "File Formats" for examples
     * 
     * @see {@link IA_FILE_FORMATS}
     */
    readonly format: IaFileFormat;
    
    /** 
     * Cryptographic hash used to verify contents of file. 32-length hex digest
     * Defined by: IA software
     * @example "4ade910556be8a15f079ac8d26a2b2e4"
     */
    readonly md5: string;

    /**
     * Source
     * 
     * Indicates whether the file was uploaded by a user (original)
     * or generated by the system (derivative or metadata)
     * 
     * Defined by: IA software
     * 
     * See {@link http://web.archive.org/web/20230111080233/https://archive.org/developers/metadata-schema/index.html#id5}
     * @example "metadata"
     */
    readonly source: IaFileSource;
    /** 
     * Unix timestamp indicating when file was last modified. 
     * @example "1706721491"
     */
    readonly mtime: `${number}`;
    /**
     * File Size
     * 
     * File size in bytes as integer
     * Defined by: IA software
     * 
     * @example 1024
     */
    readonly size: `${number}`;
};

export type IaFileBaseMetadata = Prettify<IaFileBasicMetadata & IaBaseMetadataType>;

/**
 * This type represents raw metadata as it is returned by the Internet Archive API
 * 
 * @template IaFileUserMetadata 
 */
export type IaFileSourceMetadata<IaFileUserMetadata extends IaBaseMetadataType = IaFileExtendedMetadata> =
    Prettify<IaFileBaseMetadata & Partial<IaRawMetadata<Omit<IaFileUserMetadata, keyof IaFileBasicMetadata>>>>;

export type IaFileDefinedByIaMetadata = {
    /** 
     * Cryptographic hash used to verify contents of file. 40-length hex digest
     * @example "7e88cccbe7b42dcb3286e1ea5827c5e55e879451"
     */
    readonly sha1?: string;
    /** 
     * Error-detecting code used to verify contents of file. 8-length hex digest 
     * @example "4679b176"
     */
    readonly crc32?: string;
    /**
     * Specifies if the file is an on-the-fly generated file
     * @example true
     */
    readonly otf?: boolean;
};

export type IaFileExtendedMetadata = IaFileBaseMetadata & IaFileDefinedByIaMetadata & {
    /** For derivative files, this indicates the original file the derive was performed upon. */
    original?: string;
    /** private */
    private?: boolean;
    /** Run length (in seconds). */
    length?: number;
    /** Image width (in pixels) */
    width?: number;
    /** Image height (in pixels) */
    height?: number;

    /** 
     * Camera Rotation: represents the rotation (in degrees) of the camera. Typical values are: `0`, `90`, `180`, `270`
     * @example "90"
     */
    rotation?: IaFileRotation;
    /** Track number of album. Usually an number, but occasionally has values like "2/14" (track 2 of 14) */
    track?: string;
    /** Album Name */
    album?: string;
    /** BitTorrent Info Hash */
    btih?: string;
    /** Bit Rate */
    bitrate?: string;

    /** Similar to {@link IaFileExtendedMetadata.creator}. This is a common tag used in audio files. */
    artist?: string;
    /**  */
    genre?: string;
    /**  */
    external_identifier?: string;
    /**  */
    comment?: string;
    /**  */
    original_name?: string;
    /**  */
    ctime?: string;
    /**  */
    atime?: string;
    /**  */
    wb_filtered?: string;

    /**  */
    matrix_number?: string;
    /**  */
    collection_catalog_number?: string;
    /**  */
    operatingsystem?: string;
    /**  */
    autoplay?: string;
    /** @example "youtube:2018-07-19T04:36:11Z" */
    external_identifier_match_date?: string | string[];
    /** */
    summation?: string;

    /** */
    filecount?: string;
    hocr_char_to_word_module_version?: string;
    hocr_char_to_word_hocr_version?: string;
    hocr_pageindex_module_version?: string;
    hocr_pageindex_hocr_version?: string;
    ocr_parameters?: string;
    ocr_module_version?: string;
    ocr_detected_script?: string;
    ocr_detected_script_conf?: string;
    ocr_detected_lang?: string;
    ocr_detected_lang_conf?: string;
    hocr_fts_text_module_version?: string;
    hocr_fts_text_hocr_version?: string;

    [key: `word_conf_${number}_${number}`]: string;

    /**
     * Adaptive OCR
     * @
     * Allows deriver to skip a page that would otherwise disrupt OCR
     * 
     * Defined by: uploader
     * 
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#adaptive_ocr}
     */
    adaptive_ocr?: true;

    /**
     * Date Added to Public Search
     * 
     * 2019-12 and later dates: represents time item was added to public 
     * search engine. Earlier dates: Date and time in UTC that the item was 
     * created on archive.org
     * Beginning in December 2019: when item was first added to public search engine. 
     * It is added during the first task where the item does not have noindex 
     * present in meta.xml. The field is not changed or removed if the item is 
     * subsequently removed from public search. Prior to December 2019, 
     * Addeddate was automatically set when the item directory is been created 
     * in our file system. In many cases, the addeddate will be very similar to 
     * the publicdate. However, in some cases we create an item directory with 
     * metadata but no media files prior to the media being scanned.
     * The addeddate reflects when the item was created, regardless of when 
     * the media was added to the item. When the media is added at a later date 
     * and a derive.php task is run, the publicdate will be added to the item.
     * 
     * Defined by: IA software
     * 
     * Edit access: not editable
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#addeddate}
     * @example "2017-03-28 22:05:46"
     */
    addeddate?: string;

    /**
     * Admin Collection
     * 
     * Collection will generally be suppressed from public display, e.g. in facets, membership lists on Collection/Details pages, etc.
     * Only used by internal IA admins
     * Defined by: IA admin
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#admin-collection}
     * @example true
     */
    'admin-collection'?: boolean;

    /**
     * Aspect Ratio
     * 
     * Ratio of the pixel width and height of a video stream
     * Standard values for this field are 4:3 and 16:9, but other values are possible.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#aspect_ratio}
     * @example "4:3"
     */
    aspect_ratio?: string;

    /**
     * Audio Codec
     * 
     * Program used to decode audio stream
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: IA admin
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#audio_codec}
     * @example "ac3"
     */
    audio_codec?: string;

    /**
     * Audio Sample Rate
     * 
     * Samples per second
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: IA admin
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#audio_sample_rate}
     * @example "48000"
     */
    audio_sample_rate?: string;

    /**
     * Better PDF
     * 
     * Indicates that the derive module should create a higher quality PDF derivative (distinguishes text from background better).
     * This field is either set to the value true, or is not included in meta.xml. If this field is included after the initial derive is run, user should also run a derive task to create the better quality PDF.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#betterpdf}
     * @example true
     */
    betterpdf?: boolean;

    /**
     * Bookreader defaults
     * 
     * Indicates whether the bookreader should display one or two pages by default
     * The bookreader defaults to showing books in 2up mode, so this field is generally only used to indicate that an item should be displayed in 1up mode (showing only one page at a time in the bookreader).
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#bookreader-defaults}
     * @example "mode/1up"
     */
    'bookreader-defaults'?: "mode/1up" | "mode/2up" | "mode/thumb";

    /**
     * Box ID
     * 
     * Location of physical item in the Physical Archive
     * Boxids always start with the letters IA followed by numbers. The numbers represent the container, pallet and box that the physical item is stored in. When there are multiple boxid fields in meta.xml, the first boxid listed represents the physical item that was digitized. Subsequent boxid fields represent the location of duplicate physical items.
     * Defined by: IA admin
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#boxid}
     * @example "IA158001"
     */
    boxid?: string | string[];

    /**
     * Black and White OCR
     * 
     * Allows deriver to OCR specific pages as B&W if color is causing failure.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#bwocr}
     * @example "001"
     */
    bwocr?: string;

    /**
     * Call Number
     * 
     * Contributing library's local call number
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#call_number}
     * @example "6675707"
     * @example "NC 285.1 P9287m"
     */
    call_number?: string;

    /**
     * Camera
     * 
     * Camera model used during digitization process
     * Defined by: user admin
     * Edit access: user admin
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#camera}
     * @example "Canon 5D"
     */
    camera?: string;

    /**
     * Closed Captioning Number
     * 
     * Indicates which closed captioning file should be used for display and search
     * Primarily used for TV Archive items. Closed captioning files are stored as [identifier].cc#.txt in the item. This tag indicates which cc# file to display in item and use for search indexing.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#ccnum}
     * @example "cc5"
     */
    ccnum?: string;

    /**
     * Closed Captioning
     * 
     * Indicates whether item contains closed captioning files
     * Field is generally only present when the video has closed captioning. When captioning is not present, the field may have "no" as the value, or just not be included in meta.xml
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#closed_captioning}
     * @example "yes"
     * @example "no"
     */
    closed_captioning?: "yes" | "no";

    /**
     * Collections
     * 
     * Indicates to the website what collection(s) this item belongs to.
     * Required for all items except "fav-username" collections. Always list the item's primary collection first in meta.xml; this is the collection the item "belongs" to. The primary collection often represents the entity that contributed or created the content. Uploaders can only choose from collections that they have privileges for. General uploaders with no special privs can only upload to selected "Community" collections or the test_collection. Items in the test_collection are removed from the site after 30 days. Parent collections If the parent collections of an item's collections are not already included in the item's own collection list, they will be automatically added (at the end of the next task on the item). Here, more specifically, is how that addition takes place: All of the item's currently listed collections are considered in turn. For each of them, we trace its ancestry all the way up to the top-level collection (usually a mediatype); in tracing ancestry, we consider only the primary (first-listed) parent collection at each step. If the original item is itself a collection, we include the top-level collection, otherwise we don't. Any collection we encounter during this traversal of the hierarchy that isn't already in the item's collection list gets added to the end of the list. For example, if the original item starts with collections A and B listed, we find A's primary parent (call it A-P), that collection's primary parent (A-P-P), etc., until we hit a mediatype; all of those that aren't already listed get added, including the mediatype if the item itself is a collection. Then we do the same for B and its primary parent B-P, B-P-P, etc.
     * Defined by: user admin
     * Edit access: user admin
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#collection}
     * @example "prelinger"
     */
    collection?: string | string[];

    /**
     * Color
     * 
     * Indicates whether media is in color or black and white
     * Most used values are: color, B&W (black and white) Mostly used for video items, indicates whether video is color or black and white. Can be used to indicate different kinds of color (e.g. Kodachrome).
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#color}
     * @example "color"
     */
    color?: string;

    /**
     * Condition
     * 
     * condition of media
     * Defines the condition of the media in an item. In 78s and LPs this indicates the condition of the disc or media file. For sets with multiple discs, use the condition of the lowest grade disc in the set.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#condition}
     * @example "Good"
     */
    condition?: "Mint" | "Near Mint" | "Very Good" | "Good" | "Fair" | "Worn" | "Poor" | "Fragile" | "Incomplete";

    /**
     * Visual Condition
     * 
     * Condition of the artwork or printed materials that accompany a media item
     * Defines the condition of the artwork or printed materials that accompany the media in an item. In LPs this is used for album covers and sleeves. "Incomplete" should be used when we know that artwork/printed materials are missing. "None" should be used when the item has no artwork/printed materials and we know it is not supposed to have any. "Unknown" should be used when artwork/printed material MAY be missing, but we cannot verify.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#condition-visual}
     * @example "Good"
     */
    'condition-visual'?: string;

    /**
     * Contributor
     * 
     * The person or organization that provided the physical or digital media.
     * For physical items that have been digitized, contributor represents the library or other organization that owns the physical item. For born-digital media, contributor often represents the organization responsible for the distribution of the content (e.g. a radio station or television station).
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#contributor}
     * @example "Robarts - University of Toronto"
     */
    contributor?: string;

    /**
     * Coverage
     * 
     * Geographic or subject area covered by item
     * The preferred use of this field is to signify a geographical location that relates to the item. For example, in the TV and radio collections, we use the ISO 3166 location code for the country and state/territory of the station being recorded.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#coverage}
     * @example "GB-LND"
     */
    coverage?: string | string[];

    /**
     * Creator
     * 
     * The individual(s) or organization that created the media content.
     * For items provided by libraries, the creator is often listed using the Library of Congress Name Authority Headings, {@link http://authorities.loc.gov/} For items from other sources, the creator is often listed as first name and surname. When an item was created by an organization, such as a government agency or a production company, use the full name of the organization. This field represents the entity who created the media, not the person who uploaded the media to archive.org (though these may be the same person). All alphabets supported.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#creator}
     * @example "Austen, Jane, 1775-1817"
     * @example "Ralph Burns"
     */
    creator?: string | string[];

    /**
     * Creator Alternate Script
     * 
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#creator-alt-script}
     */
    'creator-alt-script'?: boolean;

    /**
     * Curation
     * 
     * Curation state and notes
     * Curation is a compound field with "sub-fields": curator, date, state, and comment. - Curator is the email address of the person who added the curation tag. - Date is the UTC time and date the curation tag was added, in YYYYMMDDHHMMSS format. - State can be: dark, approved, freeze, un-dark or blank - Comment can be a code used by the scanning center team to indicate issues found during QA, or a text string with some other curation comment (e.g. information about why an item was frozen or made dark). Items uploaded into open collections are generally checked by malware detection software, and the curation field will contain the results of that check.
     * Defined by: IA admin
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#curation}
     * @example "[curator]lenscriv@archive.org[/curator][date]20160504125613[/date][state]approved[/state][comment]199[/comment]"
     * @example "[curator]malware@archive.org[/curator][date]20140321085621[/date][comment]checked for malware[/comment]"
     */
    curation?: string;

    /**
     * Publication Date
     * 
     * We encourage people to use YYYY, YYYY-MM, or YYYY-MM-DD for this field, but sometimes exact dates are not possible to determine. Other common usages: [YYYY] (brackets) when a date is not certain; c.a. YYYY (c.a.) when a date is approximate; and [n.d.] when a date is unknown (you may also leave the field blank in this case). If an item has a date range, such as YYYY-YYYY, we currently index only the first date in the range. Books, movies, and CDs often only have YYYY for a publication date. Magazines often have YYYY-MM for a publication date. Concerts and articles often have YYYY-MM-DD publication dates. Use the most specific verifiable date you have access to. When the item is a digitial representation of a physical piece of media (e.g. a book, a 78rpm disc, etc.) the publication date should represent the date that the specific physical item was published. A book may have been written in 1850, and then an edition was republished in 1885. If the digitized version is the edition republished in 1885, use 1885 as the publication date (not 1850).
     * 
     * Defined by: uploader
     * 
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#date}
     * @example "1965"
     * @example "2013-05-25"
     * @example "[n.d.]"
     */
    date?: string;

    /**
     * Item Description
     * 
     * Describes the media stored in the item.
     * May be about the media content (e.g. a description of the book's plot), the physical item it represents (e.g. missing or damaged pages in the physical book that was digitized), the creator of the media (e.g. author biographical info that relates to the book), or any other information that may help a user understand the item or its context. All alphabets are supported.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#description}
     * @example "Cinemascope homage to the city of San Francisco made by amateur filmmaker and inventor Tullio Pellegrini. "
     */
    description?: string | string[];

    /**
     * External Identifier
     * 
     * URLs or identifiers to outside resources that represent the media
     * External-identifier includes Uniform Resource Names (URNs) for external resources about the media in the item. The field is usually in the form of urn:namespace:identifier.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#external-identifier}
     * @example "urn:publisher_catalog_id:88697 03614 2"
     * @example "urn:pubcat:victor:18890-B"
     * @example "urn:spotify:album:3jmETApVCjXb3hWTR1IEdH"
     * @example "urn:asin:0451531396"
     * @example "acs:epub:urn:uuid:d935586b-72a7-4720-bbb9-72fe75eae0e1"
     * @example "urn:acs6:blackreconstruc00dubo:epub:38413c16-074b-4fb6-a4dc-25e93e199d5f"
     * @example "urn:mb_artist_id:6de0f914-3e60-4418-be3b-42e0feb6eb4d"
     * @example "urn:X-pwacrawlid:AWP5"
     */
    'external-identifier'?: string | string[];

    /**
     * First File Date
     * 
     * Creation date of the earliest file contained in the item
     * Primarily used for WARC items
     * Defined by: IA software
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#firstfiledate}
     * @example "20211103001952"
     */
    firstfiledate?: string;

    /**
     * Fixed PPI
     * 
     * To change the ppi to a specific resolution. Usually lower especially when jp2.zip fails
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#fixed-ppi}
     */
    'fixed-ppi'?: boolean;

    /**
     * Fold Out Count
     * 
     * Number of fold outs captured by operator
     * Fold outs are photographed on machinery other than the Scribe. This field indicates how many foldouts were captured. The value may be 0 or higher.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#foldoutcount}
     * @example "1"
     */
    foldoutcount?: string;

    /**
     * Force Update
     * 
     * For partner-funded scanned books (no boxid), this allows a MARC record in
     * the item to overwrite metadata fields in meta.xml
     * When this field is NOT present for partner scanned books (no boxid), 
     * metadata from a MARC record will only be used to automatically fill in 
     * EMPTY metadata fields in meta.xml, and fields that already have metadata 
     * in them will be left as-is. Adding force-update to the item causes MARC 
     * to overwrite all fields that can be extracted, regardless of whether they 
     * already contain information or not.
     * 
     * Defined by: uploader
     * 
     * Edit access: uploader
     * 
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#force-update}
     * @example true
     */
    'force-update'?: boolean;

    /**
     * Frames Per Second
     * 
     * Frequency at which consecutive images are displayed
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#frames_per_second}
     * @example "29.97"
     */
    frames_per_second?: string;

    /**
     * Geo Restricted
     * 
     * Limits access based on ISO-2 Country Code
     * Defined by: IA admin
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#geo_restricted}
     */
    geo_restricted?: boolean;

    /**
     * Hidden
     * 
     * Hides collection from top level navigation
     * This tag only functions on items of mediatype collection.
     * Defined by: user admin
     * Edit access: user admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#hidden}
     * @example true
     */
    hidden?: boolean;

    /**
     * ARK
     * 
     * Archival Resource Key identifier
     * 
     * [ARK](https://arks.org/)s are URLs designed to support long-term access to information objects. We store the ark:/NAAN/Name portion of the URL in meta.xml. This can be tacked on to any ARK resolver's domain to resolve the ARK, i.e. http://n2t.net/. Read about ARKs: http://n2t.net/e/ark_ids.html ARK specification: http://n2t.net/e/arkspec.txt
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#identifier-ark}
     * @example "ark:/13960/t4rj5fk7h"
     */
    'identifier-ark'?: string;

    /**
     * Local Identifier
     * 
     * Additional local identifiers
     * Fields for many identifiers exist in the schema, including isbn, issn, oclc, and call_number. The identifier-bib field is used for additional local identifiers that don't have a place elsewhere in metadata. These identifiers are unique to the institution providing the item.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#identifier-bib}
     * @example "GLAD-84064318"
     */
    'identifier-bib'?: string | string[];

    /**
     * Image Count
     * 
     * Imagecount gives an indication of the size of the content of an item (outside of file size, which is represented in the size field). Originally used only for books, the field has been repurposed over time to provide similar information for other mediatypes.
     * Texts: represents number of page images in the item TV: represents number of seconds of video in the item Web: represents number of URIs captured in the WARCs in the item CD: number of images of physical item and accompanying materials
     * Defined by: IA software
     * Edit access: IA software
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#imagecount}
     * @example "230"
     */
    imagecount?: string;

    /**
     * ISBN
     * 
     * ISBN-10 or ISBN-13
     * https://www.iso.org/standard/65483.html https://www.isbn.org/faqs_general_questions#isbn_faq5
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#isbn}
     * @example "3540212507"
     * @example "031294716X"
     */
    isbn?: string | string[];

    /**
     * ISSN
     * 
     * ISSN
     * ISSNs are identifying numbers for serials. See https://www.issn.org/understanding-the-issn/what-is-an-issn/ for clarification.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#issn}
     * @example "2528-7788"
     * @example "1943-345X"
     */
    issn?: string | string[];

    /**
     * Language
     * 
     * The language the media is written or recorded in.
     * For items provided by libraries, the language is often provided as a 3 letter MARC language code (e.g. eng), https://www.loc.gov/marc/languages/ For other items, the language is often written out as the full name (e.g. English). Not all items have a language associated with them (e.g. instrumental music), but when there is written or spoken language we are able to do some sorts of processing better when we know the language. To skip OCR on an item, set the value to None When an item contains no OCRable content, you will sometimes see the language set to zxx. Language is particularly important for text items so that we can do the best job with optical character recognition processing.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#language}
     * @example "eng"
     * @example "Italian"
     * @example "None"
     */
    language?: string | string[];

    /**
     * Last File Date
     * 
     * Date of creation of oldest file in the item
     * Primarily used for WARC items
     * Defined by: IA software
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#lastfiledate}
     * @example "20211103003910"
     */
    lastfiledate?: string;

    /**
     * LCCN
     * 
     * Library of Congress Call Number
     * https://www.loc.gov/marc/lccn_structure.html
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#lccn}
     * @example "2004045278"
     */
    lccn?: string | string[];

    /**
     * License URL
     * 
     * URL of the selected license
     * This link should point to a recognized license, like Creative Commons or GNU. For other types of rights statements, use the rights field.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#licenseurl}
     * @example "http://creativecommons.org/licenses/by-nd/3.0/"
     */
    licenseurl?: string;

    /**
     * Marc Insert Only
     * 
     * restricting the incorporation of MARC-extracted metadata to fields that currently have no value ("insert only" behavior),
     * there are certain classes of item for which we insert MARC-extracted metadata only where no value currently exists in the item metadata for that field, so that we won't overwrite any existing metadata. if their items are readily identifiable, the same restriction can be applied to those items.
     * Defined by: IA admin
     * Edit access: IA admin
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#marc-insert-only}
     * @example true
     */
    'marc-insert-only'?: boolean;

    /**
     * Type of Media
     * 
     * Mediatype tells us about the main content of the item. It is used to determine how the item is displayed on the web site and may trigger special processing depending on the types of files contained in the item.
     * texts: books, articles, newspapers, magazines, any documents with content that contains text etree: live music concerts, items should only be uploaded for artists with collections in the etree "Live Music Archive" community audio: any item where the main media content is audio files, like FLAC, mp3, WAV, etc. movies: any item where the main media content is video files, like mpeg, mov, avi, etc. software: any item where the main media content is software intended to be run on a computer or related device such as gaming devices, phones, etc. image: any item where the main media content is image files (but is not a book or other text item), like jpeg, gif, tiff, etc. data: any item where the main content is not media or web pages, such as data sets web: any item where the main content is copies of web pages, usually stored in WARC or ARC format collection: designates the item as a collection that can "contain" other items account: designates the item as being a user account page, can only be set by internal archive systems
     * Defined by: uploader
     * Edit access: IA admin
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#mediatype}
     * @example "movies"
     */
    mediatype?: string;

    /**
     * Never Index
     * 
     * Prevents RePublisher from removing noindex at the end of the texts digitization process.
     * Only used on internally digitized texts items. Normally when a text finishes the RePublisher process, the noindex tag is removed and the book is added to the public search engine. The neverindex tag prevents the removal of noindex, so books with nevrindex set to true should not end up in the public search engine.
     * Defined by: IA admin
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#neverindex}
     * @example true
     */
    neverindex?: boolean;

    /**
     * Next Item
     * 
     * IA identifier of next item from a recorded feed
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#next_item}
     * @example "BBCNEWS_20121204_090000_BBC_News"
     */
    next_item?: string;

    /**
     * No OL Import
     * 
     * Keeps books out of open library
     * Defined by: IA admin
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#no_ol_import}
     */
    no_ol_import?: boolean;

    /**
     * No Index
     * 
     * Prevents item from being indexed in public archive.org search engine
     * While the accepted practice is to have a value of "true" for this tag, the mere presence of the tag in meta.xml will actually cause the same effect regardless of the value used (including empty). In addition to not being included in the public archive.org search engine, the noindex tag will also cause the item to not be listed in the sitemap.
     * Defined by: uploader
     * Edit access: uploader
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#noindex}
     * @example true
     */
    noindex?: boolean;

    /**
     * Notes
     * 
     * additional notes about the item
     * Use the description field to describe the media stored in an item. The notes field is for additional information like condition of othe physical item, technical notes about digitization, or similar.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#notes}
     * @example []
     */
    notes?: string | string[];

    /**
     * OCLC ID
     * 
     * Identifier of same edition in OCLC records
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#oclc-id}
     * @example "37432884"
     */
    'oclc-id'?: string | string[];

    /**
     * OCR Software
     * 
     * Software package and version used for optical character recognition
     * Set during derivation process.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#ocr}
     * @example "ABBYY FineReader 8.0"
     */
    ocr?: string;

    /**
     * Open Library author
     * 
     * Open Library author
     * Correlates to the edition page on openlibrary.org. The OL edition page URL is https://openlibrary.org/books/[openlibrary_edition]
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#openlibrary_author}
     * @example "OL52922A"
     */
    openlibrary_author?: string | string[];

    /**
     * Open Library edition identifier
     * 
     * Open Library edition identifier
     * Correlates to the edition page on openlibrary.org. The OL edition page URL is https://openlibrary.org/books/[openlibrary_edition]
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#openlibrary_edition}
     * @example "OL2769393M"
     */
    openlibrary_edition?: string;

    /**
     * Open Library subject
     * 
     * Open Library subject
     * This field is currently used to supply books for carousels on the openlibrary.org home page. At some point it will also be used to import subjects from the openlibrary_work associated with the item.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#openlibrary_subject}
     * @example "openlibrary_staff_picks"
     */
    openlibrary_subject?: string | string[];

    /**
     * Open Library work identifier
     * 
     * Open Library work identifier
     * Correlates to the work page on openlibrary.org. The OL work page URL is https://openlibrary.org/works/[openlibrary_edition]
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#openlibrary_work}
     * @example "OL675783W"
     */
    openlibrary_work?: string;

    /**
     * Operator
     * 
     * Email of the person who scanned/captured the media in the item
     * usually email address. In texts this represents the person who operated the Scribe or other scanning equipment. In web items this represents the engineer responsible for the crawl.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#operator}
     * @example "associate-stephanie-kinsey@archive.org"
     */
    operator?: string;

    /**
     * Page Progression
     * 
     * Determines direction pages will be "turned" in a book
     * lr = left to right rl = right to left
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#page-progression}
     * @example "rl"
     * @example "lr"
     */
    'page-progression'?: string;

    /**
     * Possible Copyright Status
     * 
     * Information relevant to copyright status
     * Do not use this field for CC license information (see licenseurl).
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#possible-copyright-status}
     * @example "The Centers for Medicare &amp; Medicaid Services Library is unaware of any copyright restrictions for this item."
     */
    'possible-copyright-status'?: string;

    /**
     * PPI
     * 
     * Pixels per inch
     * Indicates pixels per inch for an image. The most common use case is Internet Archive digitization centers. This number is set during the book scanning process.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#ppi}
     * @example "300"
     */
    ppi?: string;

    /**
     * Previous Item
     * 
     * IA identifier of previous item from a recorded feed
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#previous_item}
     * @example "BBCNEWS_20121204_060000_Breakfast"
     */
    previous_item?: string;

    /**
     * Public Formats
     * 
     * Collection file formats that are available to users in an Access Restricted collection
     * This tag only affects items of mediatype collection and must be used in conjunction with the access-restricted tag. This tag should only be assigned by internal IA admins.
     * Defined by: IA admin
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#public-format}
     * @example "Metadata"
     */
    'public-format'?: string | string[];

    /**
     * Publisher
     * 
     * Publisher of the media
     * - Books use publisher - Movies often use production company - Music often uses record label
     * 
     * Defined by: uploader
     * 
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#publisher}
     * @example "New York : R.R. Bowker Co."
     */
    publisher?: string;

    /**
     * Related Collection
     * 
     * Adds links to related collection on a collection's "About" page
     * Defined by: user admin
     * Edit access: user admin
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#related_collection}
     */
    related_collection?: boolean;

    /**
     * Related External Identifier
     * 
     * URLs or identifiers to resources related to the media, but not representing this exact form of the work
     * Related-external-id includes URNs for media related to the media in the item, but which are not exactly the same. The primary use of this tag is to list ISBNs, LCCNs, and OCLC numbers for other editions of the same work. These IDs are used for deduplication purposes in the scanning proces.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#related-external-id}
     * @example "urn:isbn:0671038303"
     */
    'related-external-id'?: string | string[];

    /**
     * Repub State
     * 
     * Indicates the current state of a scanned book.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#repub_state}
     * @example "19"
     */
    repub_state?: string;

    /**
     * Republisher Date
     * 
     * Date and time in UTC that the item was created archive.org.
     * Set by Scribe3 software.
     * 
     * Defined by: IA software
     * 
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#republisher_date}
     * @example "20170801165730"
     */
    republisher_date?: string;

    /**
     * Republisher Operator
     * 
     * Email of the person who completed republishing the item
     * Set by Scribe3 software.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#republisher_operator}
     * @example "associate-kiana-fekette@archive.org"
     */
    republisher_operator?: string;

    /**
     * Republisher Time
     * 
     * Number of seconds required to republish text
     * Set by Scribe3 software.
     * Defined by: IA software
     * Edit access: IA software
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#republisher_time}
     * @example "504"
     */
    republisher_time?: string;

    /**
     * Rights
     * 
     * Rights statement
     * Please see licenseurl for URL-based rights designations, like Creative Commons. For other rights information or statements, use the rights field.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#rights}
     * @example "Permission is granted under the Wikimedia Foundation&#39;s "
     * @example "These National Treasury publications may not be reproduced wholly or in part without the express authorisation of the National Treasury in writing unless used for non-profit purposes."
     */
    rights?: string;

    /**
     * Run Time
     * 
     * Length of an audio or video item
     * Uploader can set this field, but most often we have determined and set this value during the derive process.
     * Defined by: IA software
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#runtime}
     * @example "00:15:00"
     * @example "2:12"
     * @example "0:23"
     */
    runtime?: string | string[];

    /**
     * Scan Date
     * 
     * The date and time in UTC that the media was captured.
     * When an physical item is scanned/digitized, scandate represents the date/time that the digitization occurred. For web items, scandate represents the date/time the first WARC file in the item was created. For TV and radio items, scandate represents the begining time of the recording. Formats: YYYYMMDDHHMMSS YYYYMMDD YYYY YYYY-MM-DD HH:MM:SS
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#scandate}
     * @example "20170329201345"
     */
    scandate?: string;

    /**
     * Scan Fee
     * 
     * Scanning fee used during billing process
     * Set by software based on parameters for each scanning partner
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#scanfee}
     * @example "100"
     * @example "300;10;200"
     * @example "0;1.45;0"
     */
    scanfee?: string;

    /**
     * Scanner
     * 
     * Machinery used to digitize or collect the media
     * Primarily an internally used field. For digitized texts this represents the individual digitization station (e.g. Scribe 2 in the New Jersey center). For web items this represents the crawl machine used to gather the data. For films this represents the film scanner. For CDs this represents the version of the scanning software used for that CD. For end-user contriuted items, this represents the software used to upload the item.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#scanner}
     * @example "scribe2.nj.archive.org"
     * @example "selenium-101.us.archive.org"
     * @example "Lasergraphics Scanstation"
     * @example "ArchiveCD Version 2.1.15"
     * @example "Internet Archive HTML5 Uploader 1.6.3"
     */
    scanner?: string;

    /**
     * Scanning Center
     * 
     * The location where a digital copy of the media item was created
     * Generally used in conjunction with our scanning services, this tag gives the location where an item was digitized, scanned or captured.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#scanningcenter}
     * @example "boston"
     */
    scanningcenter?: string;

    /**
     * Related Music by Track
     * 
     * Adds related tracks to details page
     * Defined by: IA admin
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#show_related_music_by_track}
     */
    show_related_music_by_track?: boolean;



    /**
     * Sound
     * 
     * Indicates whether media has sound or is silent
     * Most used values are: sound, silent Mostly used for video items, this field indicates whether the media has related sound or is silent.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#sound}
     * @example "sound"
     * @example "silent"
     */
    sound?: string;



    /**
     * Source Pixel Height
     * 
     * Pixel height of original video stream
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#source_pixel_height}
     * @example 480
     */
    source_pixel_height?: number;

    /**
     * Source Pixel Width
     * 
     * Pixel width of original video stream
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#source_pixel_width}
     * @example 704
     */
    source_pixel_width?: number;

    /**
     * Sponsor
     * 
     * The person or organization that funded the digitization or collection of this media.
     * For physical items (books, film, 78rpm, etc.), this represents the entity that funded the digitization/scanning work. For born-digital items (TV, Radio, Web, etc.) this represents the entity that funded the collection of the items.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#sponsor}
     * @example "Kahle-Austin Foundation"
     */
    sponsor?: string;

    /**
     * Sponsor Date
     * 
     * Billing date for scanned materials
     * Related to digitization work. Usually a date string "YYYYMMDD", but can contain notes, such as: "not to be invoiced-past billing period" "Grant ended, item not yet invoiced" "sent20111010"
     * Defined by: IA admin
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#sponsordate}
     * @example "20100531"
     */
    sponsordate?: string;

    /**
     * Local Start Time
     * 
     * Start time of program in broadcast time zone
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#start_localtime}
     * @example "2010-03-26 18:00:00"
     */
    start_localtime?: string;

    /**
     * UTC Start Time
     * 
     * Start time of program in UTC
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#start_time}
     * @example "2010-03-26 15:00:00"
     */
    start_time?: string;

    /**
     * UTC Stop Time
     * 
     * Stop time of program in UTC
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#stop_time}
     * @example "2010-03-26 16:00:00"
     */
    stop_time?: string;

    /**
     * Subject/Keyword
     * 
     * Subjects and/or topics covered by the media content
     * Books and other media objects from libraries often use Library of Congress Subject Headings, http://id.loc.gov/authorities/subjects.html. Some collections may use their own controlled vocabulary for setting subjects. Many other items use the subject field as more casual "tags." All alphabets are supported.
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#subject}
     * @example "France"
     */
    subject?: string | string[];

    /**
     * Title
     * 
     * Title of media
     * All alphabets are supported
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#title}
     * @example "San Francisco (1955 Cinemascope film)"
     */
    title?: string;


    /**
     * Skip OCR
     * 
     * Virtual Channel the video was recorded from
     * Primarily used for TV Archive items. Maps the program number as used in H.222 Program Association Tables and Program Mapping Tables to a channel number that can be entered via digits on a receiver's remote control.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#tuner}
     * @example "Virtual Ch. 24"
     */
    tuner?: string;

    /**
     * Updated
     * 
     * Timestamp in the metadata table for the last time the item's row in that table was written
     * Timestamp is typically when the last task ran on the item, but metadata updates can also be triggered manually.
     * Defined by: IA software
     * Edit access: not editable
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#updated}
     * @example "2014-12-05"
     */
    updated?: string | string[];

    /**
     * Update Date
     * 
     * Date the item was updated by updater
     * Any time an item is changed via the editxml page by the updater (see <updater> field), a corresponding <updatedate> field is added to the meta.xml. Updatedate fields are added to meta.xml in the order changes have been made, so the oldest dates are listed first.
     * Defined by: IA software
     * Edit access: not editable
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#updatedate}
     * @example "2009-03-02 21:48:28"
     */
    updatedate?: string | string[];

    /**
     * Updater
     * 
     * Screen name of the account that updated the item
     * After initial upload, when changes are made to the content of an item the account that made changes is included in the meta.xml in an <updater> field. Updater fields are added to meta.xml in the order changes have been made, so the first listed updater belongs to the oldest modification.
     * Defined by: IA software
     * Edit access: not editable
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#updater}
     * @example "tracey pooh"
     */
    updater?: string | string[];

    /**
     * UTC Offset
     * 
     * Offset between local time and UTC
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#utc_offset}
     * @example 300
     * @example -400
     */
    utc_offset?: number;

    /**
     * Video Codec
     * 
     * Program used to decode video stream
     * Primarily used for TV Archive items.
     * Defined by: IA software
     * Edit access: IA admin
     * INTERNAL USE ONLY
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#video_codec}
     * @example "mpeg2video"
     */
    video_codec?: string;

    /**
     * Virus Check
     * This tag only functions on items of mediatype collection. 
     * The tag is either present with a value of `true` or it should not be 
     * present in the item metadata at all. Currently all items uploaded into
     * the open community collections have the virus check task run on them, 
     * without needing this tag. 
     * Any other collection that needs virus checking should have this tag 
     * present in order to trigger the virus check task to run on items uploaded
     * into the collection.
     * 
     * defined by: IA software
     * edit access: IA admin
     */
    viruscheck?: "true";

    /**
     * Volume
     * 
     * Volume number or name
     * This field is not overwritten by MARC
     * Defined by: uploader
     * Edit access: uploader
     * 
     * See {@link https://archive.org/developers/metadata-schema/index.html#volume}
     * @example "15"
     */
    volume?: string;
};

export type IaFileMetadataField = keyof IaFileExtendedMetadata;

